# Numpy Basics <hr style = "border:3px solid rgb(250, 93, 211)"></hr>

Data Analyst: Marchie S. Dawal <br>
Department: Electrical Engineering 

In [10]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [21]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [23]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
my_array = my_array.T

In [28]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
np.sum(my_array,axis=0)

array([ 6, 15])

In [33]:
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [3]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [6]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [12]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [11]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar VS Panther

In [36]:
## Jaguar

In [15]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [18]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [29]:
jaguar_median = np.median(jaguar)
jaguar_median

np.float64(9.8)

In [20]:
jaguar_mode = stats.mode(jaguar)
jaguar_mode

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [47]:
jaguar_min = np.min(jaguar)
jaguar_max = np.max(jaguar)

range_jaguar = jaguar_max - jaguar_min
range_jaguar

np.float64(8.0)

In [48]:
jaguar_q1 = np.percentile(jaguar,25)
jaguar_q1

np.float64(9.4)

In [50]:
jaguar_q3 = np.percentile(jaguar,75)
jaguar_q3

np.float64(10.45)

In [52]:
IQR_jaguar = jaguar_q3 - jaguar_q1
IQR_jaguar

np.float64(1.049999999999999)

In [53]:
jaguar_var = np.var(jaguar,ddof=1)
jaguar_var

np.float64(4.86)

In [54]:
jaguar_std = np.std(jaguar,ddof=1)
jaguar_std

np.float64(2.2045407685048604)

## Panther

In [16]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1]) 
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [55]:
pan_mean = np.mean(panther)
pan_mean

np.float64(10.75)

In [56]:
pan_median = np.median(panther)
pan_median 

np.float64(9.55)

In [57]:
pan_mode = stats.mode(panther)
pan_mode

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [58]:
pan_min = np.min(panther)
pan_max = np.max(panther)

range_pan = pan_max - pan_min
range_pan

np.float64(10.9)

In [59]:
pan_q1 = np.percentile(panther,25)
pan_q1

np.float64(9.125)

In [60]:
pan_q3 = np.percentile(panther,75)
pan_q3

np.float64(10.625)

In [61]:
IQR_pan = pan_q3 - pan_q1
IQR_pan

np.float64(1.5)

In [62]:
pan_var = np.var(panther,ddof=1)
pan_var

np.float64(11.082777777777777)

In [65]:
pan_std = np.std(panther,ddof=1)
pan_std

np.float64(3.3290806204983645)